
[General]

	[General.Amulets]
		#Defines damage that speed amulet will receive on it's usage
		#Range: 0 ~ 1000
		speed_amulet_usage_dmg = 1
		#Defines damage that fire amulet will receive on it's usage
		#Range: 0 ~ 1000
		fire_amulet_usage_dmg = 1
		#Defines damage that jump amulet will receive on it's usage
		#Range: 0 ~ 1000
		jump_amulet_usage_dmg = 5
		#Defines damage that invisibility amulet will receive on it's usage
		#Range: 0 ~ 1000
		invisibility_amulet_usage_dmg = 1

