modLoader="javafml"
loaderVersion="[40,)"
license="GNU Lesser General Public License v3 (LGPLv3)"
issueTrackerURL="https://github.com/Frostygames0/elemental-amulets/issues"

    [[mods]]
      modId="elementalamulets"
      version="${file.jarVersion}"
      displayURL="https://www.curseforge.com/minecraft/mc-mods/elemental-amulets"
      updateJSONURL="https://raw.githubusercontent.com/Frostygames0/Elemental-Amulets/1.16.5/update.json"
      logoFile="logo.png"
      displayName="Elemental Amulets"
      authors="Frostygames0"
      description= "This mod adds amulets, magical necklaces that give you cool abilities and some other cool things!"

      [[dependencies.elementalamulets]]
        modId="forge"
        mandatory=true
        versionRange="[40,)"
        ordering="NONE"
        side="BOTH"

      [[dependencies.elementalamulets]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.18.2]"
        ordering="NONE"
        side="BOTH"

      [[dependencies.elementalamulets]]
        modId="curios"
        mandatory=true
        versionRange="[1.18.2-5.0.6.3,)"

      #[[dependencies.elementalamulets]]
        #modId="patchouli"
        #mandatory=false
        #versionRange="[1.18.1-65,)"

